"""empty message

Revision ID: 71959b304cb6
Revises: c252be63e3f4
Create Date: 2022-12-16 10:54:23.323629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71959b304cb6'
down_revision = 'c252be63e3f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('year', sa.String(length=150), nullable=False),
    sa.Column('make', sa.String(length=200), nullable=True),
    sa.Column('model', sa.String(length=20), nullable=True),
    sa.Column('color', sa.String(length=200), nullable=True),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car')
    # ### end Alembic commands ###
